matrix:
  include:
    - env: PLATFORM=debian-jessie UPSTREAM_ORIGIN=true
    - env: PLATFORM=debian-jessie UPSTREAM_ORIGIN=false

sudo: required

dist: trusty

language: python

services:
  - docker

script:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run -e "ORIGIN=$UPSTREAM_ORIGIN" --name $PLATFORM test-$PLATFORM

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
