matrix:
  include:
    - env: PLATFORM=debian-jessie ORIGIN=debian
    - env: PLATFORM=debian-jessie ORIGIN=upstream

sudo: required

language: python

services:
  - docker

script:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run -e "ORIGIN=$ORIGIN" --name $PLATFORM test-$PLATFORM

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
