env:
  - PLATFORM=debian-wheezy UPSTREAM=true
  - PLATFORM=debian-jessie UPSTREAM=true
  - PLATFORM=debian-wheezy UPSTREAM=false
  - PLATFORM=debian-jessie UPSTREAM=false

sudo: required

language: python

services:
  - docker

script:
  - docker build -f tests/$PLATFORM.Dockerfile -t test-$PLATFORM . && docker run --name $PLATFORM test-$PLATFORM
