---

- name: SET_FACT | Bypass https://github.com/ansible/ansible/issues/19874
  set_fact:
    ansible_distribution_release: 'buster'
  when: ansible_facts.distribution_major_version == "buster/sid"

- name: IMPORT_TASKS | Install upstream repository
  import_tasks: upstream.yml
  when: nodejs_upstream

- name: APT | Install NodeJS
  apt:
    pkg: "nodejs"
    update_cache: yes
    cache_valid_time: 3600

- name: APT | Install NPM
  apt:
    pkg: "npm"
    default_release: "{{ ansible_distribution_release if ansible_distribution_release != 'stretch' else 'stretch-backports' }}"
  when: not nodejs_upstream
