---

- name: IMPORT_TASKS | Install upstream repository
  import_tasks: upstream.yml
  when: nodejs_upstream

- name: APT | Install NodeJS
  apt:
    pkg: "nodejs"
    update_cache: yes
    cache_valid_time: 3600
