---

- name: APT | Install apt packages
  apt:
    pkg: "{{ pkgs }}"
    update_cache: yes
    cache_valid_time: 3600
  vars:
    pkgs:
      - apt-transport-https
      - gpg

- name: APT_KEY | Get GPG key
  apt_key:
    url: https://deb.nodesource.com/gpgkey/nodesource.gpg.key

- name: APT_REPOSITORY | Add repository
  apt_repository:
    repo: 'deb https://deb.nodesource.com/node_{{ nodejs_upstream_version }}.x {{ ansible_distribution_release }} main'

- name: APT_REPOSITORY | Add src repository
  apt_repository:
    repo: 'deb-src https://deb.nodesource.com/node_{{ nodejs_upstream_version }}.x {{ ansible_distribution_release }} main'
  when: nodejs_upstream_src
